apiVersion: v1
kind: Service
metadata:
  name: eq-docs-ui-stage
  namespace: equabli-stage-nm
  labels:
    app: eq-docs-ui-app-stage
spec:
  type: ClusterIP
  ports:
  - port: 8011
    targetPort: 80
  selector:
    app: eq-docs-ui-app-stage
