apiVersion: v1
kind: Service
metadata:
  name: eq-react-ui-qa
  namespace: equabli-qa-nm
  labels:
    app: eq-react-ui-app-qa
spec:
  type: ClusterIP
  ports:
  - port: 8011
    targetPort: 80
  selector:
    app: eq-react-ui-app-qa

