declare global {
    interface Window {
        BASE_URL: string;
        BASE_URL1: string;
        LOGIN_URL: string;
        COMMON_URL: string;
        CLIENT_URL: string;
        COMPLIANCE_SEARCH_URL: string;
        CONSUMER_URL: string;
        BASE_URL2: string;
        COMMON_ENTITY_SERVICE: string;
        JOB_SERVICE: string;
        VENDOR_INTEGRATION: string;
        ACCOUNT_SERVICE: string;
        ADDRESS_SERVICE: string;
        INVENTORY_SERVICE: string;
        CLIENT_SERVICE: string;
        CONSUMER_SERVICE: string;
        PHONE_SERVICE: string;
        EMAIL_SERVICE: string;
        ALERT_SERVICE: string;
        PAYMENT_SERVICE: string;
        PARTNER_SERVICE: string;
        STATE_SERVICE: string;
        SCHEDULER_SERVICE: string;
        ALERT_MANAGEMENT: string;
        BUSINESS_PROCESS_MANAGEMENT: string;
        VENDOR_MANAGEMENT: string;
        BATCH_SCHEDULER_MANAGEMENT: string;
        CONFIGURATION_MANAGEMENT: string;
        SUSPECTED_MANAGEMENT: string;
        REPORT: string;
        AWS_SERVICE: string;
        COMMUNICATION_SERVICE: string;
        AWS_QUICKSIGHT_URL: string;
        SCOPES: string[];
        REDIRECT_URL: string;
        POST_LOGOUT_URL: string;
        TENANT_URL: string;
    }
}

// =====================================
//            AUTHENTICATION Types
// =====================================

export const AuthTypes: any = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_RESET: "LOGIN_RESET",
    LOGOUT: "LOGOUT"
}

// =====================================
//            NOTIFICATION Types
// =====================================

export const NotificationTypes: any = {
    GET_NOTIFICATION: "GET_NOTIFICATION",
    SET_NOTIFICATION: "SET_NOTIFICATION"
}

// =====================================
//            SEARCH Types
// =====================================

export const AccountSearch: any = {
    ACCOUNT_RESET: "ACCOUNT_RESET",
    ACCOUNTS_REQUEST: "ACCOUNTS_REQUEST",
    ACCOUNTS_SUCCESS: "ACCOUNTS_SUCCESS",
    ACCOUNTS_FAILURE: "ACCOUNTS_FAILURE",
}

export const ConsumerSearch: any = {
    CONSUMER_RESET: "CONSUMER_RESET",
    CONSUMER_REQUEST: "CONSUMER_REQUEST",
    CONSUMER_SUCCESS: "CONSUMER_SUCCESS",
    CONSUMER_FAILURE: "CONSUMER_FAILURE",
}

// =====================================
//            INVENTORY Types
// =====================================

export const InventorySearch: any = {
    INVENTORY_RESET: "INVENTORY_RESET",
    INVENTORY_REQUEST: "INVENTORY_REQUEST",
    INVENTORY_SUCCESS: "INVENTORY_SUCCESS",
    INVENTORY_FAILURE: "INVENTORY_FAILURE",
}

// =====================================
//            ACTION QUEUE Types
// =====================================

export const AccountQueue: any = {
    ACTION_QUEUE_REQUEST: "ACTION_QUEUE_REQUEST",
    ACTION_QUEUE_SUCCESS: "ACTION_QUEUE_SUCCESS",
    ACTION_QUEUE_FAILURE: "ACTION_QUEUE_FAILURE",
    ACTION_QUEUE_RESET: "ACTION_QUEUE_RESET",
}

export const ApproverAction: any = {
    APPROVER_ACTION_REQUEST: "APPROVER_ACTION_REQUEST",
    APPROVER_ACTION_SUCCESS: "APPROVER_ACTION_SUCCESS",
    APPROVER_ACTION_FAILURE: "APPROVER_ACTION_FAILURE",
    APPROVER_ACTION_RESET: "APPROVER_ACTION_RESET",
}

// =====================================
//            ACTION ITEMS Types
// =====================================
export const MyRequests: any = {
    MY_REQUESTS_REQUEST: "MY_REQUESTS_REQUEST",
    MY_REQUESTS_SUCCESS: "MY_REQUESTS_SUCCESS",
    MY_REQUESTS_FAILURE: "MY_REQUESTS_FAILURE",
    MY_REQUESTS_RESET: "MY_REQUESTS_RESET",
}

export const PendingForApproval: any = {
    PENDING_FOR_APPROVAL_REQUEST: "PENDING_FOR_APPROVAL_REQUEST",
    PENDING_FOR_APPROVAL_SUCCESS: "PENDING_FOR_APPROVAL_SUCCESS",
    PENDING_FOR_APPROVAL_FAILURE: "PENDING_FOR_APPROVAL_FAILURE",
    PENDING_FOR_APPROVAL_RESET: "PENDING_FOR_APPROVAL_RESET",
}

export const AllRequests: any = {
    ALL_REQUESTS_REQUEST: "ALL_REQUESTS_REQUEST",
    ALL_REQUESTS_SUCCESS: "ALL_REQUESTS_SUCCESS",
    ALL_REQUESTS_FAILURE: "ALL_REQUESTS_FAILURE",
    ALL_REQUESTS_RESET: "ALL_REQUESTS_RESET",
}

// =====================================
//            COMMON Types
// =====================================

export const ComplianceMode: any = {
    COMPLIANCE_MODE_REQUEST: "COMPLIANCE_MODE_REQUEST",
    COMPLIANCE_MODE_SUCCESS: "COMPLIANCE_MODE_SUCCESS",
    COMPLIANCE_MODE_FAILURE: "COMPLIANCE_MODE_FAILURE"
}

export const Clients: any = {
    CLIENTS_REQUEST: "CLIENTS_REQUEST",
    CLIENTS_SUCCESS: "CLIENTS_SUCCESS",
    CLIENTS_FAILURE: "CLIENTS_FAILURE"
}

export const AgencyName: any = {
    AGENCY_REQUEST: "AGENCY_REQUEST",
    AGENCY_SUCCESS: "AGENCY_SUCCESS",
    AGENCY_FAILURE: "AGENCY_FAILURE",
}

export const AccountConfig: any = {
    ACCOUNT_CONFIG_REQUEST: "ACCOUNT_CONFIG_REQUEST",
    ACCOUNT_CONFIG_SUCCESS: "ACCOUNT_CONFIG_SUCCESS",
    ACCOUNT_CONFIG_FAILURE: "ACCOUNT_CONFIG_FAILURE",
    ACCOUNT_CONFIG_RESET: "ACCOUNT_CONFIG_RESET"
}

export const Status: any = {
    STATUS_REQUEST: "STATUS_REQUEST",
    STATUS_SUCCESS: "STATUS_SUCCESS",
    STATUS_FAILURE: "STATUS_FAILURE",
}

export const States: any = {
    STATE_REQUEST: "STATE_REQUEST",
    STATE_SUCCESS: "STATE_SUCCESS",
    STATE_FAILURE: "STATE_FAILURE"
}

export const ComplianceCategory: any = {
    COMPLIANCE_CATEGORY_REQUEST: "COMPLIANCE_CATEGORY_REQUEST",
    COMPLIANCE_CATEGORY_SUCCESS: "COMPLIANCE_CATEGORY_SUCCESS",
    COMPLIANCE_CATEGORY_FAILURE: "COMPLIANCE_CATEGORY_FAILURE"
}

export const ComplianceType: any = {
    COMPLIANCE_TYPE_REQUEST: "COMPLIANCE_TYPE_REQUEST",
    COMPLIANCE_TYPE_SUCCESS: "COMPLIANCE_TYPE_SUCCESS",
    COMPLIANCE_TYPE_FAILURE: "COMPLIANCE_TYPE_FAILURE"
}

export const ComplianceStatus: any = {
    COMPLIANCE_STATUS_REQUEST: "COMPLIANCE_STATUS_REQUEST",
    COMPLIANCE_STATUS_SUCCESS: "COMPLIANCE_STATUS_SUCCESS",
    COMPLIANCE_STATUS_FAILURE: "COMPLIANCE_STATUS_FAILURE"
}

export const ComplianceReason: any = {
    COMPLIANCE_REASON_REQUEST: "COMPLIANCE_REASON_REQUEST",
    COMPLIANCE_REASON_SUCCESS: "COMPLIANCE_REASON_SUCCESS",
    COMPLIANCE_REASON_FAILURE: "COMPLIANCE_REASON_FAILURE"
}

export const ComplianceChannel: any = {
    COMPLIANCE_CHANNEL_REQUEST: "COMPLIANCE_CHANNEL_REQUEST",
    COMPLIANCE_CHANNEL_SUCCESS: "COMPLIANCE_CHANNEL_SUCCESS",
    COMPLIANCE_CHANNEL_FAILURE: "COMPLIANCE_CHANNEL_FAILURE"
}

export const Regulatory: any = {
    REGULATORY_REQUEST: "REGULATORY_REQUEST",
    REGULATORY_SUCCESS: "REGULATORY_SUCCESS",
    REGULATORY_FAILURE: "REGULATORY_FAILURE"
}

export const AppId: any = {
    APP_ID_REQUEST: "APP_ID_REQUEST",
    APP_ID_SUCCESS: "APP_ID_SUCCESS",
    APP_ID_FAILURE: "APP_ID_FAILURE"
}

export const RecordStatus: any = {
    RECORD_STATUS_REQUEST: "RECORD_STATUS_REQUEST",
    RECORD_STATUS_SUCCESS: "RECORD_STATUS_SUCCESS",
    RECORD_STATUS_FAILURE: "RECORD_STATUS_FAILURE"
}

export const RecordSource: any = {
    RECORD_SOURCE_REQUEST: "RECORD_SOURCE_REQUEST",
    RECORD_SOURCE_SUCCESS: "RECORD_SOURCE_SUCCESS",
    RECORD_SOURCE_FAILURE: "RECORD_SOURCE_FAILURE"
}

export const DocTypes: any = {
    DOC_TYPES_REQUEST: "DOC_TYPES_REQUEST",
    DOC_TYPES_SUCCESS: "DOC_TYPES_SUCCESS",
    DOC_TYPES_FAILURE: "DOC_TYPES_FAILURE"
}

export const CommunicationChannel: any = {
    COMMUNICATION_CHANNEL_REQUEST: "COMMUNICATION_CHANNEL_REQUEST",
    COMMUNICATION_CHANNEL_SUCCESS: "COMMUNICATION_CHANNEL_SUCCESS",
    COMMUNICATION_CHANNEL_FAILURE: "COMMUNICATION_CHANNEL_FAILURE"
}

export const CommunicationType: any = {
    COMMUNICATION_TYPE_REQUEST: "COMMUNICATION_TYPE_REQUEST",
    COMMUNICATION_TYPE_SUCCESS: "COMMUNICATION_TYPE_SUCCESS",
    COMMUNICATION_TYPE_FAILURE: "COMMUNICATION_TYPE_FAILURE"
}

export const BankruptcyType: any = {
    BANKRUPTCY_TYPE_REQUEST: "BANKRUPTCY_TYPE_REQUEST",
    BANKRUPTCY_TYPE_SUCCESS: "BANKRUPTCY_TYPE_SUCCESS",
    BANKRUPTCY_TYPE_FAILURE: "BANKRUPTCY_TYPE_FAILURE"
}

export const TimeZones: any = {
    TIME_ZONE_REQUEST: "TIME_ZONE_REQUEST",
    TIME_ZONE_SUCCESS: "TIME_ZONE_SUCCESS",
    TIME_ZONE_FAILURE: "TIME_ZONE_FAILURE"
}

export const PlacementReconciliationStatus: any = {
    PLACEMENT_RECONCILIATION_STATUS_REQUEST: "PLACEMENT_RECONCILIATION_STATUS_REQUEST",
    PLACEMENT_RECONCILIATION_STATUS_SUCCESS: "PLACEMENT_RECONCILIATION_STATUS_SUCCESS",
    PLACEMENT_RECONCILIATION_STATUS_FAILURE: "PLACEMENT_RECONCILIATION_STATUS_FAILURE",
    PLACEMENT_RECONCILIATION_STATUS_RESET: "PLACEMENT_RECONCILIATION_STATUS_RESET"
}

export const LogIssue: any = {
    LOG_ISSUE: "LOG_ISSUE"
}

export const ReportingIssue: any = {
    REPORTING_ISSUE_REQUESTED: "REPORTING_ISSUE_REQUESTED",
    REPORTING_ISSUE_SUCCESS: "REPORTING_ISSUE_SUCCESS",
    REPORTING_ISSUE_FAILURE: "REPORTING_ISSUE_FAILURE",
    REPORTING_ISSUE_RESET: "REPORTING_ISSUE_RESET"
}

// =====================================
//            COMPLIANCE SEARCH
// =====================================

export const ComplianceSearch: any = {
    COMPLIANCE_SEARCH_REQUEST: "COMPLIANCE_SEARCH_REQUEST",
    COMPLIANCE_SEARCH_SUCCESS: "COMPLIANCE_SEARCH_SUCCESS",
    COMPLIANCE_SEARCH_FAILURE: "COMPLIANCE_SEARCH_FAILURE",
    COMPLIANCE_SEARCH_RESET: "COMPLIANCE_SEARCH_RESET"
}

// =====================================
//            CREATE COMPLIANCE 
// =====================================

export const CreateComplianceSearch: any = {
    CREATE_COMPLIANCE_SEARCH_REQUEST: "CREATE_COMPLIANCE_SEARCH_REQUEST",
    CREATE_COMPLIANCE_SEARCH_SUCCESS: "CREATE_COMPLIANCE_SEARCH_SUCCESS",
    CREATE_COMPLIANCE_SEARCH_FAILURE: "CREATE_COMPLIANCE_SEARCH_FAILURE",
    CREATE_COMPLIANCE_SEARCH_RESET: "CREATE_COMPLIANCE_SEARCH_RESET"
}

export const CreateComplianceRequest: any = {
    CREATE_COMPLIANCE_REQUEST_REQUEST: "CREATE_COMPLIANCE_REQUEST_REQUEST",
    CREATE_COMPLIANCE_REQUEST_SUCCESS: "CREATE_COMPLIANCE_REQUEST_SUCCESS",
    CREATE_COMPLIANCE_REQUEST_FAILURE: "CREATE_COMPLIANCE_REQUEST_FAILURE",
    CREATE_COMPLIANCE_REQUEST_RESET: "CREATE_COMPLIANCE_REQUEST_RESET"
}

export const Types: any = {
    TYPES_REQUEST: "TYPES_REQUEST",
    TYPES_SUCCESS: "TYPES_SUCCESS",
    TYPES_FAILURE: "TYPES_FAILURE"
}

export const PhoneTypes: any = {
    PHONE_TYPES_REQUEST: "PHONE_TYPES_REQUEST",
    PHONE_TYPES_SUCCESS: "PHONE_TYPES_SUCCESS",
    PHONE_TYPES_FAILURE: "PHONE_TYPES_FAILURE"
}

export const AddressTypes: any = {
    ADDRESS_TYPES_REQUEST: "ADDRESS_TYPES_REQUEST",
    ADDRESS_TYPES_SUCCESS: "ADDRESS_TYPES_SUCCESS",
    ADDRESS_TYPES_FAILURE: "ADDRESS_TYPES_FAILURE"
}

export const ComplianceHierarchy: any = {
    COMPLIANCE_HIERARCHY_REQUEST: "COMPLIANCE_HIERARCHY_REQUEST",
    COMPLIANCE_HIERARCHY_SUCCESS: "COMPLIANCE_HIERARCHY_SUCCESS",
    COMPLIANCE_HIERARCHY_FAILURE: "COMPLIANCE_HIERARCHY_FAILURE",
    COMPLIANCE_HIERARCHY_RESET: "COMPLIANCE_HIERARCHY_RESET"
}


// ======================================
//        ACCOUNT DETAIL PAGE
// ======================================

export const AccountDetail: any = {
    ACCOUNT_DETAIL_REQUEST: "ACCOUNT_DETAIL_REQUEST",
    ACCOUNT_DETAIL_SUCCESS: "ACCOUNT_DETAIL_SUCCESS",
    ACCOUNT_DETAIL_FAILURE: "ACCOUNT_DETAIL_FAILURE"
}

export const AccountPaymentHistory: any = {
    ACCOUNT_PAYMENT_HISTORY_REQUEST: "ACCOUNT_PAYMENT_HISTORY_REQUEST",
    ACCOUNT_PAYMENT_HISTORY_SUCCESS: "ACCOUNT_PAYMENT_HISTORY_SUCCESS",
    ACCOUNT_PAYMENT_HISTORY_FAILURE: "ACCOUNT_PAYMENT_HISTORY_FAILURE"
}

export const AccountPaymentPlanHistory: any = {
    ACCOUNT_PAYMENT_PLAN_HISTORY_REQUEST: "ACCOUNT_PAYMENT_PLAN_HISTORY_REQUEST",
    ACCOUNT_PAYMENT_PLAN_HISTORY_SUCCESS: "ACCOUNT_PAYMENT_PLAN_HISTORY_SUCCESS",
    ACCOUNT_PAYMENT_PLAN_HISTORY_FAILURE: "ACCOUNT_PAYMENT_PLAN_HISTORY_FAILURE"
}

export const AccountCommunicationHistory: any = {
    ACCOUNT_COMMUNICATION_HISTORY_REQUEST: "ACCOUNT_COMMUNICATION_HISTORY_REQUEST",
    ACCOUNT_COMMUNICATION_HISTORY_SUCCESS: "ACCOUNT_COMMUNICATION_HISTORY_SUCCESS",
    ACCOUNT_COMMUNICATION_HISTORY_FAILURE: "ACCOUNT_COMMUNICATION_HISTORY_FAILURE"
}

export const AccountHistory: any = {
    ACCOUNT_HISTORY_REQUEST: "ACCOUNT_HISTORY_REQUEST",
    ACCOUNT_HISTORY_SUCCESS: "ACCOUNT_HISTORY_SUCCESS",
    ACCOUNT_HISTORY_FAILURE: "ACCOUNT_HISTORY_FAILURE"
}

export const AccountLedger: any = {
    ACCOUNT_LEDGER_REQUEST: "ACCOUNT_LEDGER_REQUEST",
    ACCOUNT_LEDGER_SUCCESS: "ACCOUNT_LEDGER_SUCCESS",
    ACCOUNT_LEDGER_FAILURE: "ACCOUNT_LEDGER_FAILURE"
}


// ======================================
//        CONSUMER DETAIL PAGE
// ======================================

export const ConsumerDetail: any = {
    CONSUMER_DETAIL_REQUEST: "CONSUMER_DETAIL_REQUEST",
    CONSUMER_DETAIL_SUCCESS: "CONSUMER_DETAIL_SUCCESS",
    CONSUMER_DETAIL_FAILURE: "CONSUMER_DETAIL_FAILURE"
}

export const ConsumerHistory: any = {
    CONSUMER_HISTORY_REQUEST: "CONSUMER_HISTORY_REQUEST",
    CONSUMER_HISTORY_SUCCESS: "CONSUMER_HISTORY_SUCCESS",
    CONSUMER_HISTORY_FAILURE: "CONSUMER_HISTORY_FAILURE"
}

export const ConsumerAddress: any = {
    CONSUMER_ADDRESS_REQUEST: "CONSUMER_ADDRESS_REQUEST",
    CONSUMER_ADDRESS_SUCCESS: "CONSUMER_ADDRESS_SUCCESS",
    CONSUMER_ADDRESS_FAILURE: "CONSUMER_ADDRESS_FAILURE"
}

export const ConsumerAddAddress: any = {
    CONSUMER_ADD_ADDRESS_REQUEST: "CONSUMER_ADD_ADDRESS_REQUEST",
    CONSUMER_ADD_ADDRESS_SUCCESS: "CONSUMER_ADD_ADDRESS_SUCCESS",
    CONSUMER_ADD_ADDRESS_FAILURE: "CONSUMER_ADD_ADDRESS_FAILURE",
    CONSUMER_ADD_ADDRESS_RESET: "CONSUMER_ADD_ADDRESS_RESET"
}

export const ConsumerEditAddress: any = {
    CONSUMER_EDIT_ADDRESS_REQUEST: "CONSUMER_EDIT_ADDRESS_REQUEST",
    CONSUMER_EDIT_ADDRESS_SUCCESS: "CONSUMER_EDIT_ADDRESS_SUCCESS",
    CONSUMER_EDIT_ADDRESS_FAILURE: "CONSUMER_EDIT_ADDRESS_FAILURE",
    CONSUMER_EDIT_ADDRESS_RESET: "CONSUMER_EDIT_ADDRESS_RESET"
}

export const ConsumerDeleteAddress: any = {
    CONSUMER_DELETE_ADDRESS_REQUEST: "CONSUMER_DELETE_ADDRESS_REQUEST",
    CONSUMER_DELETE_ADDRESS_SUCCESS: "CONSUMER_DELETE_ADDRESS_SUCCESS",
    CONSUMER_DELETE_ADDRESS_FAILURE: "CONSUMER_DELETE_ADDRESS_FAILURE",
    CONSUMER_DELETE_ADDRESS_RESET: "CONSUMER_DELETE_ADDRESS_RESET"
}

export const ConsumerPhones: any = {
    CONSUMER_PHONES_REQUEST: "CONSUMER_PHONES_REQUEST",
    CONSUMER_PHONES_SUCCESS: "CONSUMER_PHONES_SUCCESS",
    CONSUMER_PHONES_FAILURE: "CONSUMER_PHONES_FAILURE"
}

export const ConsumerAddPhone: any = {
    CONSUMER_ADD_PHONE_REQUEST: "CONSUMER_ADD_PHONE_REQUEST",
    CONSUMER_ADD_PHONE_SUCCESS: "CONSUMER_ADD_PHONE_SUCCESS",
    CONSUMER_ADD_PHONE_FAILURE: "CONSUMER_ADD_PHONE_FAILURE",
    CONSUMER_ADD_PHONE_RESET: "CONSUMER_ADD_PHONE_RESET"
}

export const ConsumerEditPhone: any = {
    CONSUMER_EDIT_PHONE_REQUEST: "CONSUMER_EDIT_PHONE_REQUEST",
    CONSUMER_EDIT_PHONE_SUCCESS: "CONSUMER_EDIT_PHONE_SUCCESS",
    CONSUMER_EDIT_PHONE_FAILURE: "CONSUMER_EDIT_PHONE_FAILURE",
    CONSUMER_EDIT_PHONE_RESET: "CONSUMER_EDIT_PHONE_RESET"
}

export const ConsumerDeletePhone: any = {
    CONSUMER_DELETE_PHONE_REQUEST: "CONSUMER_DELETE_PHONE_REQUEST",
    CONSUMER_DELETE_PHONE_SUCCESS: "CONSUMER_DELETE_PHONE_SUCCESS",
    CONSUMER_DELETE_PHONE_FAILURE: "CONSUMER_DELETE_PHONE_FAILURE",
    CONSUMER_DELETE_PHONE_RESET: "CONSUMER_DELETE_PHONE_RESET"
}

export const ConsumerEmails: any = {
    CONSUMER_EMAILS_REQUEST: "CONSUMER_EMAILS_REQUEST",
    CONSUMER_EMAILS_SUCCESS: "CONSUMER_EMAILS_SUCCESS",
    CONSUMER_EMAILS_FAILURE: "CONSUMER_EMAILS_FAILURE"
}

export const ConsumerAddEmail: any = {
    CONSUMER_ADD_EMAIL_REQUEST: "CONSUMER_ADD_EMAIL_REQUEST",
    CONSUMER_ADD_EMAIL_SUCCESS: "CONSUMER_ADD_EMAIL_SUCCESS",
    CONSUMER_ADD_EMAIL_FAILURE: "CONSUMER_ADD_EMAIL_FAILURE",
    CONSUMER_ADD_EMAIL_RESET: "CONSUMER_ADD_EMAIL_RESET"
}

export const ConsumerEditEmail: any = {
    CONSUMER_EDIT_EMAIL_REQUEST: "CONSUMER_EDIT_EMAIL_REQUEST",
    CONSUMER_EDIT_EMAIL_SUCCESS: "CONSUMER_EDIT_EMAIL_SUCCESS",
    CONSUMER_EDIT_EMAIL_FAILURE: "CONSUMER_EDIT_EMAIL_FAILURE",
    CONSUMER_EDIT_EMAIL_RESET: "CONSUMER_EDIT_EMAIL_RESET"
}

export const ConsumerDeleteEmail: any = {
    CONSUMER_DELETE_EMAIL_REQUEST: "CONSUMER_DELETE_EMAIL_REQUEST",
    CONSUMER_DELETE_EMAIL_SUCCESS: "CONSUMER_DELETE_EMAIL_SUCCESS",
    CONSUMER_DELETE_EMAIL_FAILURE: "CONSUMER_DELETE_EMAIL_FAILURE",
    CONSUMER_DELETE_EMAIL_RESET: "CONSUMER_DELETE_EMAIL_RESET"
}

export const AddressStatus: any = {
    ADDRESS_STATUS_REQUEST: "ADDRESS_STATUS_REQUEST",
    ADDRESS_STATUS_SUCCESS: "ADDRESS_STATUS_SUCCESS",
    ADDRESS_STATUS_FAILURE: "ADDRESS_STATUS_FAILURE",
    ADDRESS_STATUS_RESET: "ADDRESS_STATUS_RESET"
}

// ======================================
//        ALERTS PAGE
// ======================================

export const Alerts: any = {
    ALERTS_REQUEST: "ALERTS_REQUEST",
    ALERTS_SUCCESS: "ALERTS_SUCCESS",
    ALERTS_FAILURE: "ALERTS_FAILURE"
}

export const AlertTypes: any = {
    ALERTS_TYPES_REQUEST: "ALERTS_TYPES_REQUEST",
    ALERTS_TYPES_SUCCESS: "ALERTS_TYPES_SUCCESS",
    ALERTS_TYPES_FAILURE: "ALERTS_TYPES_FAILURE"
}

export const AlertGroup: any = {
    ALERTS_GROUP_REQUEST: "ALERTS_GROUP_REQUEST",
    ALERTS_GROUP_SUCCESS: "ALERTS_GROUP_SUCCESS",
    ALERTS_GROUP_FAILURE: "ALERTS_GROUP_FAILURE"
}

export const AlertCreate: any = {
    ALERTS_CREATE_REQUEST: "ALERTS_CREATE_REQUEST",
    ALERTS_CREATE_SUCCESS: "ALERTS_CREATE_SUCCESS",
    ALERTS_CREATE_FAILURE: "ALERTS_CREATE_FAILURE",
    ALERTS_CREATE_RESET: "ALERTS_CREATE_RESET"
}

export const AlertUpdate: any = {
    ALERTS_UPDATE_REQUEST: "ALERTS_UPDATE_REQUEST",
    ALERTS_UPDATE_SUCCESS: "ALERTS_UPDATE_SUCCESS",
    ALERTS_UPDATE_FAILURE: "ALERTS_UPDATE_FAILURE",
    ALERTS_UPDATE_RESET: "ALERTS_UPDATE_RESET"
}

export const AlertDelete: any = {
    ALERTS_DELETE_REQUEST: "ALERTS_DELETE_REQUEST",
    ALERTS_DELETE_SUCCESS: "ALERTS_DELETE_SUCCESS",
    ALERTS_DELETE_FAILURE: "ALERTS_DELETE_FAILURE",
    ALERTS_DELETE_RESET: "ALERTS_DELETE_RESET"
}


// ======================================
//        BATCH SCHEDULER PAGE
// ======================================

export const Scheduler: any = {
    SCHEDULER_REQUEST: "SCHEDULER_REQUEST",
    SCHEDULER_SUCCESS: "SCHEDULER_SUCCESS",
    SCHEDULER_FAILURE: "SCHEDULER_FAILURE"
}

export const BatchSchedulerGroup: any = {
    BATCH_SCHEDULER_GROUP_REQUEST: "BATCH_SCHEDULER_GROUP_REQUEST",
    BATCH_SCHEDULER_GROUP_SUCCESS: "BATCH_SCHEDULER_GROUP_SUCCESS",
    BATCH_SCHEDULER_GROUP_FAILURE: "BATCH_SCHEDULER_GROUP_FAILURE"
}

export const BatchSchedulerCreate: any = {
    BATCH_SCHEDULER_CREATE_REQUEST: "BATCH_SCHEDULER_CREATE_REQUEST",
    BATCH_SCHEDULER_CREATE_SUCCESS: "BATCH_SCHEDULER_CREATE_SUCCESS",
    BATCH_SCHEDULER_CREATE_FAILURE: "BATCH_SCHEDULER_CREATE_FAILURE",
    BATCH_SCHEDULER_CREATE_RESET: "BATCH_SCHEDULER_CREATE_RESET"
}

export const BatchSchedulerUpdate: any = {
    BATCH_SCHEDULER_UPDATE_REQUEST: "BATCH_SCHEDULER_UPDATE_REQUEST",
    BATCH_SCHEDULER_UPDATE_SUCCESS: "BATCH_SCHEDULER_UPDATE_SUCCESS",
    BATCH_SCHEDULER_UPDATE_FAILURE: "BATCH_SCHEDULER_UPDATE_FAILURE",
    BATCH_SCHEDULER_UPDATE_RESET: "BATCH_SCHEDULER_UPDATE_RESET",
}

export const BatchSchedulerDelete: any = {
    BATCH_SCHEDULER_DELETE_REQUEST: "BATCH_SCHEDULER_DELETE_REQUEST",
    BATCH_SCHEDULER_DELETE_SUCCESS: "BATCH_SCHEDULER_DELETE_SUCCESS",
    BATCH_SCHEDULER_DELETE_FAILURE: "BATCH_SCHEDULER_DELETE_FAILURE",
    BATCH_SCHEDULER_DELETE_RESET: "BATCH_SCHEDULER_DELETE_RESET"
}

export const BatchSchedulerRun: any = {
    BATCH_SCHEDULER_RUN_REQUEST: "BATCH_SCHEDULER_RUN_REQUEST",
    BATCH_SCHEDULER_RUN_SUCCESS: "BATCH_SCHEDULER_RUN_SUCCESS",
    BATCH_SCHEDULER_RUN_FAILURE: "BATCH_SCHEDULER_RUN_FAILURE",
    BATCH_SCHEDULER_RUN_RESET: "BATCH_SCHEDULER_RUN_RESET"
}

export const BatchSchedulerExecute: any = {
    BATCH_SCHEDULER_EXECUTE_REQUEST: "BATCH_SCHEDULER_EXECUTE_REQUEST",
    BATCH_SCHEDULER_EXECUTE_SUCCESS: "BATCH_SCHEDULER_EXECUTE_SUCCESS",
    BATCH_SCHEDULER_EXECUTE_FAILURE: "BATCH_SCHEDULER_EXECUTE_FAILURE",
    BATCH_SCHEDULER_EXECUTE_RESET: "BATCH_SCHEDULER_EXECUTE_RESET"
}

// ======================================
//        PROCESS DASHBOARD
// ======================================

export const processDashboardAlertManagement: any = {
    PROCESS_DASHBOARD_ALERT_REQUEST: "PROCESS_DASHBOARD_ALERT_REQUEST",
    PROCESS_DASHBOARD_ALERT_SUCCESS: "PROCESS_DASHBOARD_ALERT_SUCCESS",
    PROCESS_DASHBOARD_ALERT_FAILURE: "PROCESS_DASHBOARD_ALERT_FAILURE",
    PROCESS_DASHBOARD_ALERT_RESET: "PROCESS_DASHBOARD_ALERT_RESET"
}

export const processDashboardDetails: any = {
    PROCESS_DASHBOARD_DETAILS_REQUEST: "PROCESS_DASHBOARD_DETAILS_REQUEST",
    PROCESS_DASHBOARD_DETAILS_SUCCESS: "PROCESS_DASHBOARD_DETAILS_SUCCESS",
    PROCESS_DASHBOARD_DETAILS_FAILURE: "PROCESS_DASHBOARD_DETAILS_FAILURE",
    PROCESS_DASHBOARD_DETAILS_RESET: "PROCESS_DASHBOARD_DETAILS_RESET"
}

export const processDashboardBusinessManagement: any = {
    PROCESS_DASHBOARD_BUSINESS_REQUEST: "PROCESS_DASHBOARD_BUSINESS_REQUEST",
    PROCESS_DASHBOARD_BUSINESS_SUCCESS: "PROCESS_DASHBOARD_BUSINESS_SUCCESS",
    PROCESS_DASHBOARD_BUSINESS_FAILURE: "PROCESS_DASHBOARD_BUSINESS_FAILURE",
    PROCESS_DASHBOARD_BUSINESS_RESET: "PROCESS_DASHBOARD_BUSINESS_RESET"
}

export const processDashboardVendorManagement: any = {
    PROCESS_DASHBOARD_VENDOR_REQUEST: "PROCESS_DASHBOARD_VENDOR_REQUEST",
    PROCESS_DASHBOARD_VENDOR_SUCCESS: "PROCESS_DASHBOARD_VENDOR_SUCCESS",
    PROCESS_DASHBOARD_VENDOR_FAILURE: "PROCESS_DASHBOARD_VENDOR_FAILURE",
    PROCESS_DASHBOARD_VENDOR_RESET: "PROCESS_DASHBOARD_VENDOR_RESET"
}

export const processDashboardBatchSchedulerManagement: any = {
    PROCESS_DASHBOARD_SCHEDULER_REQUEST: "PROCESS_DASHBOARD_SCHEDULER_REQUEST",
    PROCESS_DASHBOARD_SCHEDULER_SUCCESS: "PROCESS_DASHBOARD_SCHEDULER_SUCCESS",
    PROCESS_DASHBOARD_SCHEDULER_FAILURE: "PROCESS_DASHBOARD_SCHEDULER_FAILURE",
    PROCESS_DASHBOARD_SCHEDULER_RESET: "PROCESS_DASHBOARD_SCHEDULER_RESET"
}

// ======================================
//        CONFIGURATION MANAGEMENT
// ======================================

export const masterManagement: any = {
    MASTER_MANAGEMENT_REQUEST: "MASTER_MANAGEMENT_REQUEST",
    MASTER_MANAGEMENT_SUCCESS: "MASTER_MANAGEMENT_SUCCESS",
    MASTER_MANAGEMENT_FAILURE: "MASTER_MANAGEMENT_FAILURE",
    MASTER_MANAGEMENT_RESET: "MASTER_MANAGEMENT_RESET"
}

export const insertMasterManagement: any = {
    INSERT_MASTER_MANAGEMENT_REQUEST: "INSERT_MASTER_MANAGEMENT_REQUEST",
    INSERT_MASTER_MANAGEMENT_SUCCESS: "INSERT_MASTER_MANAGEMENT_SUCCESS",
    INSERT_MASTER_MANAGEMENT_FAILURE: "INSERT_MASTER_MANAGEMENT_FAILURE",
    INSERT_MASTER_MANAGEMENT_RESET: "INSERT_MASTER_MANAGEMENT_RESET"
}

export const masterManagementUpdate: any = {
    MASTER_MANAGEMENT_UPDATE_REQUEST: "MASTER_MANAGEMENT_UPDATE_REQUEST",
    MASTER_MANAGEMENT_UPDATE_SUCCESS: "MASTER_MANAGEMENT_UPDATE_SUCCESS",
    MASTER_MANAGEMENT_UPDATE_FAILURE: "MASTER_MANAGEMENT_UPDATE_FAILURE",
    MASTER_MANAGEMENT_UPDATE_RESET: "MASTER_MANAGEMENT_UPDATE_RESET"
}

export const AppConfigTypes: any = {
    APP_CONFIG_TYPES_REQUEST: "APP_CONFIG_TYPES_REQUEST",
    APP_CONFIG_TYPES_SUCCESS: "APP_CONFIG_TYPES_SUCCESS",
    APP_CONFIG_TYPES_FAILURE: "APP_CONFIG_TYPES_FAILURE",
    APP_CONFIG_TYPES_RESET: "APP_CONFIG_TYPES_RESET"
}

export const AppConfigValue: any = {
    APP_CONFIG_VALUE_REQUEST: "APP_CONFIG_VALUE_REQUEST",
    APP_CONFIG_VALUE_SUCCESS: "APP_CONFIG_VALUE_SUCCESS",
    APP_CONFIG_VALUE_FAILURE: "APP_CONFIG_VALUE_FAILURE",
    APP_CONFIG_VALUE_RESET: "APP_CONFIG_VALUE_RESET"
}

export const AppConfigValueUpdate: any = {
    APP_CONFIG_VALUE_UPDATE_REQUEST: "APP_CONFIG_VALUE_UPDATE_REQUEST",
    APP_CONFIG_VALUE_UPDATE_SUCCESS: "APP_CONFIG_VALUE_UPDATE_SUCCESS",
    APP_CONFIG_VALUE_UPDATE_FAILURE: "APP_CONFIG_VALUE_UPDATE_FAILURE",
    APP_CONFIG_VALUE_UPDATE_RESET: "APP_CONFIG_VALUE_UPDATE_RESET"
}

export const AppConfigValueInsert: any = {
    APP_CONFIG_VALUE_INSERT_REQUEST: "APP_CONFIG_VALUE_INSERT_REQUEST",
    APP_CONFIG_VALUE_INSERT_SUCCESS: "APP_CONFIG_VALUE_INSERT_SUCCESS",
    APP_CONFIG_VALUE_INSERT_FAILURE: "APP_CONFIG_VALUE_INSERT_FAILURE",
    APP_CONFIG_VALUE_INSERT_RESET: "APP_CONFIG_VALUE_INSERT_RESET"
}


// ======================================
//        Scrubbing
// ======================================

export const Scrubbing: any = {
    SCRUBBING_REQUEST: "SCRUBBING_REQUEST",
    SCRUBBING_SUCCESS: "SCRUBBING_SUCCESS",
    SCRUBBING_FAILURE: "SCRUBBING_FAILURE",
    SCRUBBING_RESET: "SCRUBBING_RESET"
}

export const ScrubbingDetails: any = {
    SCRUBBING_DETAILS_REQUEST: "SCRUBBING_DETAILS_REQUEST",
    SCRUBBING_DETAILS_SUCCESS: "SCRUBBING_DETAILS_SUCCESS",
    SCRUBBING_DETAILS_FAILURE: "SCRUBBING_DETAILS_FAILURE",
    SCRUBBING_DETAILS_RESET: "SCRUBBING_DETAILS_RESET"
}

// ======================================
//        Scrubbing
// ======================================
export const Report: any = {
    REPORT_REQUEST: "REPORT_REQUEST",
    REPORT_SUCCESS: "REPORT_SUCCESS",
    REPORT_FAILURE: "REPORT_FAILURE",
    REPORT_RESET: "REPORT_RESET"
}

// ======================================
//        Scrubbing
// ======================================
export const SolManagement: any = {
    SOL_MANAGEMENT_REQUEST: "SOL_MANAGEMENT_REQUEST",
    SOL_MANAGEMENT_SUCCESS: "SOL_MANAGEMENT_SUCCESS",
    SOL_MANAGEMENT_FAILURE: "SOL_MANAGEMENT_FAILURE",
    SOL_MANAGEMENT_RESET: "SOL_MANAGEMENT_RESET"
}

export const updateSol: any = {
    SOL_UPDATE_REQUEST: "SOL_UPDATE_REQUEST",
    SOL_UPDATE_SUCCESS: "SOL_UPDATE_SUCCESS",
    SOL_UPDATE_FAILURE: "SOL_UPDATE_FAILURE",
    SOL_UPDATE_RESET: "SOL_UPDATE_RESET",
}

// ======================================
//        Scrubbing
// ======================================

export const PlacementReconciliation: any = {
    PLACEMENT_RECONCILIATION_REQUEST: "PLACEMENT_RECONCILIATION_REQUEST",
    PLACEMENT_RECONCILIATION_SUCCESS: "PLACEMENT_RECONCILIATION_SUCCESS",
    PLACEMENT_RECONCILIATION_FAILURE: "PLACEMENT_RECONCILIATION_FAILURE",
    PLACEMENT_RECONCILIATION_RESET: "PLACEMENT_RECONCILIATION_RESET",
}

// ======================================
//        Download report
// ======================================
export const AppData: any = {
    APP_DATA_REQUEST: "APP_DATA_REQUEST",
    APP_DATA_SUCCESS: "APP_DATA_SUCCESS",
    APP_DATA_FAILURE: "APP_DATA_FAILURE",
    APP_DATA_RESET: "APP_DATA_RESET",
}

export const ReportDownload: any = {
    DOWNLOAD_REPORT_REQUEST: "DOWNLOAD_REPORT_REQUEST",
    DOWNLOAD_REPORT_SUCCESS: "DOWNLOAD_REPORT_SUCCESS",
    DOWNLOAD_REPORT_FAILURE: "DOWNLOAD_REPORT_FAILURE",
    DOWNLOAD_REPORT_RESET: "DOWNLOAD_REPORT_RESET",
}

// ======================================
//        Dashboard
// ======================================
export const Dashboard: any = {
    DASHBOARD_REQUEST: "DASHBOARD_REQUEST",
    DASHBOARD_SUCCESS: "DASHBOARD_SUCCESS",
    DASHBOARD_FAILURE: "DASHBOARD_FAILURE",
    DASHBOARD_RESET: "DASHBOARD_RESET",
}

export const DashboardWidgetList: any = {
    DASHBOARD_WIDGET_LIST_REQUEST: "DASHBOARD_WIDGET_LIST_REQUEST",
    DASHBOARD_WIDGET_LIST_SUCCESS: "DASHBOARD_WIDGET_LIST_SUCCESS",
    DASHBOARD_WIDGET_LIST_FAILURE: "DASHBOARD_WIDGET_LIST_FAILURE",
    DASHBOARD_WIDGET_LIST_RESET: "DASHBOARD_WIDGET_LIST_RESET",
}

export const DashboardPreference: any = {
    DASHBOARD_PREFERENCE_REQUEST: "DASHBOARD_PREFERENCE_REQUEST",
    DASHBOARD_PREFERENCE_SUCCESS: "DASHBOARD_PREFERENCE_SUCCESS",
    DASHBOARD_PREFERENCE_FAILURE: "DASHBOARD_PREFERENCE_FAILURE",
    DASHBOARD_PREFERENCE_RESET: "DASHBOARD_PREFERENCE_RESET",
}

// ======================================
//        Registration
// ======================================
export const Registration: any = {
    REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
    REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
    REGISTRATION_FAILURE: "REGISTRATION_FAILURE",
    REGISTRATION_RESET: "REGISTRATION_RESET",
}

export const validateOrgName: any = {
    ORG_NAME_VALIDATION_REQUEST: "ORG_NAME_VALIDATION_REQUEST",
    ORG_NAME_VALIDATION_SUCCESS: "ORG_NAME_VALIDATION_SUCCESS",
    ORG_NAME_VALIDATION_FAILURE: "ORG_NAME_VALIDATION_FAILURE",
    ORG_NAME_VALIDATION_RESET: "ORG_NAME_VALIDATION_RESET",
}


// ========================================
// Compliance details page
// ========================================

export const AdditionTimeRequired: any = {
    ADDITION_TIME_REQUIRED_REQUESTED: "ADDITION_TIME_REQUIRED_REQUESTED",
    ADDITION_TIME_REQUIRED_SUCCESS: "ADDITION_TIME_REQUIRED_SUCCESS",
    ADDITION_TIME_REQUIRED_FAILURE: "ADDITION_TIME_REQUIRED_FAILURE",
    ADDITION_TIME_REQUIRED_RESET: "ADDITION_TIME_REQUIRED_RESET",
}


export const CommunicationOutcome: any = {
    COMMUNICATION_OUTCOME_REQUESTED: 'COMMUNICATION_OUTCOME_REQUESTED',
    COMMUNICATION_OUTCOME_SUCCESS: 'COMMUNICATION_OUTCOME_SUCCESS',
    COMMUNICATION_OUTCOME_FAILURE: 'COMMUNICATION_OUTCOME_FAILURE',
    COMMUNICATION_OUTCOME_RESET: 'COMMUNICATION_OUTCOME_RESET'
}

export const CommunicationReason: any = {
    COMMUNICATION_REASON_REQUESTED: 'COMMUNICATION_REASON_REQUESTED',
    COMMUNICATION_REASON_SUCCESS: 'COMMUNICATION_REASON_SUCCESS',
    COMMUNICATION_REASON_FAILURE: 'COMMUNICATION_REASON_FAILURE',
    COMMUNICATION_REASON_RESET: 'COMMUNICATION_REASON_RESET'
}

// ========================================
// Eligible partner page
// ========================================

export const ServiceOffered: any = {
    SERVICE_OFFERED_REQUESTED: 'SERVICE_OFFERED_REQUESTED',
    SERVICE_OFFERED_SUCCESS: 'SERVICE_OFFERED_SUCCESS',
    SERVICE_OFFERED_FAILURE: 'SERVICE_OFFERED_FAILURE',
    SERVICE_OFFERED_RESET: 'SERVICE_OFFERED_RESET'
}
export const PartnerStatus: any = {
    PARTNER_STATUS_REQUESTED: 'PARTNER_STATUS_REQUESTED',
    PARTNER_STATUS_SUCCESS: 'PARTNER_STATUS_SUCCESS',
    PARTNER_STATUS_FAILURE: 'PARTNER_STATUS_FAILURE',
    PARTNER_STATUS_RESET: 'PARTNER_STATUS_RESET'
}
export const EligiblePartners: any = {
    ELIGIBLE_PARTNERS_REQUESTED: 'ELIGIBLE_PARTNERS_REQUESTED',
    ELIGIBLE_PARTNERS_SUCCESS: 'ELIGIBLE_PARTNERS_SUCCESS',
    ELIGIBLE_PARTNERS_FAILURE: 'ELIGIBLE_PARTNERS_FAILURE',
    ELIGIBLE_PARTNERS_RESET: 'ELIGIBLE_PARTNERS_RESET'
}
