declare global {
    interface Window {
        BASE_URL: string;
        BASE_URL1: string;
        LOGIN_URL: string;
        COMMON_URL: string;
        CLIENT_URL: string;
        COMPLIANCE_SEARCH_URL: string;
        CONSUMER_URL: string;
        BASE_URL2: string;
        COMMON_ENTITY_SERVICE: string;
        JOB_SERVICE: string;
        VENDOR_INTEGRATION: string;
        ACCOUNT_SERVICE: string;
        ADDRESS_SERVICE: string;
        INVENTORY_SERVICE: string;
        CLIENT_SERVICE: string;
        CONSUMER_SERVICE: string;
        PHONE_SERVICE: string;
        EMAIL_SERVICE: string;
        ALERT_SERVICE: string;
        PAYMENT_SERVICE: string;
        PARTNER_SERVICE: string;
        STATE_SERVICE: string;
        SCHEDULER_SERVICE: string;
        ALERT_MANAGEMENT: string;
        BUSINESS_PROCESS_MANAGEMENT: string;
        VENDOR_MANAGEMENT: string;
        BATCH_SCHEDULER_MANAGEMENT: string;
        CONFIGURATION_MANAGEMENT: string;
        SUSPECTED_MANAGEMENT: string;
        REPORT: string;
        AWS_SERVICE: string;
        COMMUNICATION_SERVICE: string;
        AWS_QUICKSIGHT_URL: string;
        SCOPES: string[];
        REDIRECT_URL: string;
        POST_LOGOUT_URL: string;
        TENANT_URL: string;
    }
}

// =====================================
//            AUTHENTICATION Types
// =====================================

export const AuthTypes: any = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_RESET: "LOGIN_RESET",
    LOGOUT: "LOGOUT"
}

// =====================================
//            COMMON Types
// =====================================

export const ComplianceMode: any = {
    COMPLIANCE_MODE_REQUEST: "COMPLIANCE_MODE_REQUEST",
    COMPLIANCE_MODE_SUCCESS: "COMPLIANCE_MODE_SUCCESS",
    COMPLIANCE_MODE_FAILURE: "COMPLIANCE_MODE_FAILURE"
}

export const Clients: any = {
    CLIENTS_REQUEST: "CLIENTS_REQUEST",
    CLIENTS_SUCCESS: "CLIENTS_SUCCESS",
    CLIENTS_FAILURE: "CLIENTS_FAILURE"
}

export const AgencyName: any = {
    AGENCY_REQUEST: "AGENCY_REQUEST",
    AGENCY_SUCCESS: "AGENCY_SUCCESS",
    AGENCY_FAILURE: "AGENCY_FAILURE",
}

export const AccountConfig: any = {
    ACCOUNT_CONFIG_REQUEST: "ACCOUNT_CONFIG_REQUEST",
    ACCOUNT_CONFIG_SUCCESS: "ACCOUNT_CONFIG_SUCCESS",
    ACCOUNT_CONFIG_FAILURE: "ACCOUNT_CONFIG_FAILURE",
    ACCOUNT_CONFIG_RESET: "ACCOUNT_CONFIG_RESET"
}

export const Status: any = {
    STATUS_REQUEST: "STATUS_REQUEST",
    STATUS_SUCCESS: "STATUS_SUCCESS",
    STATUS_FAILURE: "STATUS_FAILURE",
}

export const States: any = {
    STATE_REQUEST: "STATE_REQUEST",
    STATE_SUCCESS: "STATE_SUCCESS",
    STATE_FAILURE: "STATE_FAILURE"
}

export const ComplianceCategory: any = {
    COMPLIANCE_CATEGORY_REQUEST: "COMPLIANCE_CATEGORY_REQUEST",
    COMPLIANCE_CATEGORY_SUCCESS: "COMPLIANCE_CATEGORY_SUCCESS",
    COMPLIANCE_CATEGORY_FAILURE: "COMPLIANCE_CATEGORY_FAILURE"
}

export const ComplianceType: any = {
    COMPLIANCE_TYPE_REQUEST: "COMPLIANCE_TYPE_REQUEST",
    COMPLIANCE_TYPE_SUCCESS: "COMPLIANCE_TYPE_SUCCESS",
    COMPLIANCE_TYPE_FAILURE: "COMPLIANCE_TYPE_FAILURE"
}

export const ComplianceStatus: any = {
    COMPLIANCE_STATUS_REQUEST: "COMPLIANCE_STATUS_REQUEST",
    COMPLIANCE_STATUS_SUCCESS: "COMPLIANCE_STATUS_SUCCESS",
    COMPLIANCE_STATUS_FAILURE: "COMPLIANCE_STATUS_FAILURE"
}

export const ComplianceReason: any = {
    COMPLIANCE_REASON_REQUEST: "COMPLIANCE_REASON_REQUEST",
    COMPLIANCE_REASON_SUCCESS: "COMPLIANCE_REASON_SUCCESS",
    COMPLIANCE_REASON_FAILURE: "COMPLIANCE_REASON_FAILURE"
}

export const ComplianceChannel: any = {
    COMPLIANCE_CHANNEL_REQUEST: "COMPLIANCE_CHANNEL_REQUEST",
    COMPLIANCE_CHANNEL_SUCCESS: "COMPLIANCE_CHANNEL_SUCCESS",
    COMPLIANCE_CHANNEL_FAILURE: "COMPLIANCE_CHANNEL_FAILURE"
}

export const Regulatory: any = {
    REGULATORY_REQUEST: "REGULATORY_REQUEST",
    REGULATORY_SUCCESS: "REGULATORY_SUCCESS",
    REGULATORY_FAILURE: "REGULATORY_FAILURE"
}

export const AppId: any = {
    APP_ID_REQUEST: "APP_ID_REQUEST",
    APP_ID_SUCCESS: "APP_ID_SUCCESS",
    APP_ID_FAILURE: "APP_ID_FAILURE"
}

export const RecordStatus: any = {
    RECORD_STATUS_REQUEST: "RECORD_STATUS_REQUEST",
    RECORD_STATUS_SUCCESS: "RECORD_STATUS_SUCCESS",
    RECORD_STATUS_FAILURE: "RECORD_STATUS_FAILURE"
}

export const RecordSource: any = {
    RECORD_SOURCE_REQUEST: "RECORD_SOURCE_REQUEST",
    RECORD_SOURCE_SUCCESS: "RECORD_SOURCE_SUCCESS",
    RECORD_SOURCE_FAILURE: "RECORD_SOURCE_FAILURE"
}

export const DocTypes: any = {
    DOC_TYPES_REQUEST: "DOC_TYPES_REQUEST",
    DOC_TYPES_SUCCESS: "DOC_TYPES_SUCCESS",
    DOC_TYPES_FAILURE: "DOC_TYPES_FAILURE"
}

export const CommunicationChannel: any = {
    COMMUNICATION_CHANNEL_REQUEST: "COMMUNICATION_CHANNEL_REQUEST",
    COMMUNICATION_CHANNEL_SUCCESS: "COMMUNICATION_CHANNEL_SUCCESS",
    COMMUNICATION_CHANNEL_FAILURE: "COMMUNICATION_CHANNEL_FAILURE"
}

export const CommunicationType: any = {
    COMMUNICATION_TYPE_REQUEST: "COMMUNICATION_TYPE_REQUEST",
    COMMUNICATION_TYPE_SUCCESS: "COMMUNICATION_TYPE_SUCCESS",
    COMMUNICATION_TYPE_FAILURE: "COMMUNICATION_TYPE_FAILURE"
}

export const BankruptcyType: any = {
    BANKRUPTCY_TYPE_REQUEST: "BANKRUPTCY_TYPE_REQUEST",
    BANKRUPTCY_TYPE_SUCCESS: "BANKRUPTCY_TYPE_SUCCESS",
    BANKRUPTCY_TYPE_FAILURE: "BANKRUPTCY_TYPE_FAILURE"
}


// ======================================
//        Registration
// ======================================
export const Registration: any = {
    REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
    REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
    REGISTRATION_FAILURE: "REGISTRATION_FAILURE",
    REGISTRATION_RESET: "REGISTRATION_RESET",
}

export const validateOrgName: any = {
    ORG_NAME_VALIDATION_REQUEST: "ORG_NAME_VALIDATION_REQUEST",
    ORG_NAME_VALIDATION_SUCCESS: "ORG_NAME_VALIDATION_SUCCESS",
    ORG_NAME_VALIDATION_FAILURE: "ORG_NAME_VALIDATION_FAILURE",
    ORG_NAME_VALIDATION_RESET: "ORG_NAME_VALIDATION_RESET",
}

// ======================================
//        File Name Configuration
// ======================================

export const Conjunction: any = {
    CONJUNCTION_REQUEST: 'CONJUNCTION_REQUEST',
    CONJUNCTION_SUCCESS: "CONJUNCTION_SUCCESS",
    CONJUNCTION_FAILURE: "CONJUNCTION_FAILURE",
    CONJUNCTION_RESET: "CONJUNCTION_RESET",
}

export const FieldOptions: any = {
    FIELD_OPTIONS_REQUEST: 'FIELD_OPTIONS_REQUEST',
    FIELD_OPTIONS_SUCCESS: "FIELD_OPTIONS_SUCCESS",
    FIELD_OPTIONS_FAILURE: "FIELD_OPTIONS_FAILURE",
    FIELD_OPTIONS_RESET: "FIELD_OPTIONS_RESET",
}

export const RetentionPolicy: any = {
    RETENTION_POLICY_REQUEST: 'RETENTION_POLICY_REQUEST',
    RETENTION_POLICY_SUCCESS: "RETENTION_POLICY_SUCCESS",
    RETENTION_POLICY_FAILURE: "RETENTION_POLICY_FAILURE",
    RETENTION_POLICY_RESET: "RETENTION_POLICY_RESET",
}

export const DocumentPolicy: any = {
    DOCUMENT_POLICY_REQUEST: 'DOCUMENT_POLICY_REQUEST',
    DOCUMENT_POLICY_SUCCESS: "DOCUMENT_POLICY_SUCCESS",
    DOCUMENT_POLICY_FAILURE: "DOCUMENT_POLICY_FAILURE",
    DOCUMENT_POLICY_RESET: "DOCUMENT_POLICY_RESET",
}

export const UserFileNamingConfig: any = {
    USER_FILE_NAMING_CONFIG_REQUEST: 'USER_FILE_NAMING_CONFIG_REQUEST',
    USER_FILE_NAMING_CONFIG_SUCCESS: 'USER_FILE_NAMING_CONFIG_SUCCESS',
    USER_FILE_NAMING_CONFIG_FAILURE: 'USER_FILE_NAMING_CONFIG_FAILURE',
    USER_FILE_NAMING_CONFIG_RESET: 'USER_FILE_NAMING_CONFIG_RESET'
}

export const UserRetentionPolicy: any = {
    USER_RETENTION_POLICY_REQUEST: 'USER_RETENTION_POLICY_REQUEST',
    USER_RETENTION_POLICY_SUCCESS: 'USER_RETENTION_POLICY_SUCCESS',
    USER_RETENTION_POLICY_FAILURE: 'USER_RETENTION_POLICY_FAILURE',
    USER_RETENTION_POLICY_RESET: 'USER_RETENTION_POLICY_RESET'
}

export const UserSeparator: any = {
    USER_SEPARATOR_REQUEST: 'USER_SEPARATOR_REQUEST',
    USER_SEPARATOR_SUCCESS: 'USER_SEPARATOR_SUCCESS',
    USER_SEPARATOR_FAILURE: 'USER_SEPARATOR_FAILURE',
    USER_SEPARATOR_RESET: 'USER_SEPARATOR_RESET'
}

export const UserDocumentPolicy: any = {
    USER_DOCUMENT_POLICY_REQUEST: 'USER_DOCUMENT_POLICY_REQUEST',
    USER_DOCUMENT_POLICY_SUCCESS: 'USER_DOCUMENT_POLICY_SUCCESS',
    USER_DOCUMENT_POLICY_FAILURE: 'USER_DOCUMENT_POLICY_FAILURE',
    USER_DOCUMENT_POLICY_RESET: 'USER_DOCUMENT_POLICY_RESET'
}

export const SaveUserConfiguration: any = {
    SAVE_USER_CONFIG_REQUEST: 'SAVE_USER_CONFIG_REQUEST',
    SAVE_USER_CONFIG_SUCCESS: 'SAVE_USER_CONFIG_SUCCESS',
    SAVE_USER_CONFIG_FAILURE: 'SAVE_USER_CONFIG_FAILURE',
    SAVE_USER_CONFIG_RESET: 'SAVE_USER_CONFIG_RESET'
}

export const ConnectedUsers: any = {
    CONNECTED_USER_REQUEST: 'CONNECTED_USER_REQUEST',
    CONNECTED_USER_SUCCESS: 'CONNECTED_USER_SUCCESS',
    CONNECTED_USER_FAILURE: 'CONNECTED_USER_FAILURE',
    CONNECTED_USER_RESET: 'CONNECTED_USER_RESET'
}

// =========================================
// My Documents
// =========================================

export const MyDocumentsFolder: any = {
    MY_DOCUMENTS_FOLDER_REQUEST: 'MY_DOCUMENTS_FOLDER_REQUEST',
    MY_DOCUMENTS_FOLDER_SUCCESS: "MY_DOCUMENTS_FOLDER_SUCCESS",
    MY_DOCUMENTS_FOLDER_FAILURE: "MY_DOCUMENTS_FOLDER_FAILURE",
    MY_DOCUMENTS_FOLDER_RESET: "MY_DOCUMENTS_FOLDER_RESET",
}

export const MyDocumentsList: any = {
    MY_DOCUMENTS_LIST_REQUEST: 'MY_DOCUMENTS_LIST_REQUEST',
    MY_DOCUMENTS_LIST_SUCCESS: "MY_DOCUMENTS_LIST_SUCCESS",
    MY_DOCUMENTS_LIST_FAILURE: "MY_DOCUMENTS_LIST_FAILURE",
    MY_DOCUMENTS_LIST_RESET: "MY_DOCUMENTS_LIST_RESET",
}

export const DocumentsType: any = {
    DOCUMENTS_TYPE_REQUEST: 'DOCUMENTS_TYPE_REQUEST',
    DOCUMENTS_TYPE_SUCCESS: "DOCUMENTS_TYPE_SUCCESS",
    DOCUMENTS_TYPE_FAILURE: "DOCUMENTS_TYPE_FAILURE",
    DOCUMENTS_TYPE_RESET: "DOCUMENTS_TYPE_RESET",
}

export const ProductTypes: any = {
    PRODUCT_TYPE_REQUEST: 'PRODUCT_TYPE_REQUEST',
    PRODUCT_TYPE_SUCCESS: "PRODUCT_TYPE_SUCCESS",
    PRODUCT_TYPE_FAILURE: "PRODUCT_TYPE_FAILURE",
    PRODUCT_TYPE_RESET: "PRODUCT_TYPE_RESET"
}

// =========================================
// Document const
// =========================================
export const DocumentsCost: any = {
    DOCUMENTS_COST_REQUEST: 'DOCUMENTS_COST_REQUEST',
    DOCUMENTS_COST_SUCCESS: "DOCUMENTS_COST_SUCCESS",
    DOCUMENTS_COST_FAILURE: "DOCUMENTS_COST_FAILURE",
    DOCUMENTS_COST_RESET: "DOCUMENTS_COST_RESET",
}

export const SaveDocumentsCost: any = {
    SAVE_DOCUMENTS_COST_REQUEST: 'SAVE_DOCUMENTS_COST_REQUEST',
    SAVE_DOCUMENTS_COST_SUCCESS: "SAVE_DOCUMENTS_COST_SUCCESS",
    SAVE_DOCUMENTS_COST_FAILURE: "SAVE_DOCUMENTS_COST_FAILURE",
    SAVE_DOCUMENTS_COST_RESET: "SAVE_DOCUMENTS_COST_RESET",
}

export const DeleteDocumentsCost: any = {
    DELETE_DOCUMENTS_COST_REQUEST: 'DELETE_DOCUMENTS_COST_REQUEST',
    DELETE_DOCUMENTS_COST_SUCCESS: "DELETE_DOCUMENTS_COST_SUCCESS",
    DELETE_DOCUMENTS_COST_FAILURE: "DELETE_DOCUMENTS_COST_FAILURE",
    DELETE_DOCUMENTS_COST_RESET: "DELETE_DOCUMENTS_COST_RESET",
}

export const EditDocumentsCost: any = {
    EDIT_DOCUMENTS_COST_REQUEST: 'EDIT_DOCUMENTS_COST_REQUEST',
    EDIT_DOCUMENTS_COST_SUCCESS: "EDIT_DOCUMENTS_COST_SUCCESS",
    EDIT_DOCUMENTS_COST_FAILURE: "EDIT_DOCUMENTS_COST_FAILURE",
    EDIT_DOCUMENTS_COST_RESET: "EDIT_DOCUMENTS_COST_RESET",
}

// =========================================
// Required Documents
// =========================================
export const RequiredDocuments: any = {
    REQUIRED_DOCUMENTS_REQUEST: 'REQUIRED_DOCUMENTS_REQUEST',
    REQUIRED_DOCUMENTS_SUCCESS: "REQUIRED_DOCUMENTS_SUCCESS",
    REQUIRED_DOCUMENTS_FAILURE: "REQUIRED_DOCUMENTS_FAILURE",
    REQUIRED_DOCUMENTS_RESET: "REQUIRED_DOCUMENTS_RESET",
}

export const SaveRequiredDocuments: any = {
    SAVE_REQUIRED_DOCUMENTS_REQUEST: 'SAVE_REQUIRED_DOCUMENTS_REQUEST',
    SAVE_REQUIRED_DOCUMENTS_SUCCESS: "SAVE_REQUIRED_DOCUMENTS_SUCCESS",
    SAVE_REQUIRED_DOCUMENTS_FAILURE: "SAVE_REQUIRED_DOCUMENTS_FAILURE",
    SAVE_REQUIRED_DOCUMENTS_RESET: "SAVE_REQUIRED_DOCUMENTS_RESET",
}

export const EditRequiredDocuments: any = {
    EDIT_REQUIRED_DOCUMENTS_REQUEST: 'EDIT_REQUIRED_DOCUMENTS_REQUEST',
    EDIT_REQUIRED_DOCUMENTS_SUCCESS: "EDIT_REQUIRED_DOCUMENTS_SUCCESS",
    EDIT_REQUIRED_DOCUMENTS_FAILURE: "EDIT_REQUIRED_DOCUMENTS_FAILURE",
    EDIT_REQUIRED_DOCUMENTS_RESET: "EDIT_REQUIRED_DOCUMENTS_RESET",
}

export const DeleteRequiredDocuments: any = {
    DELETE_REQUIRED_DOCUMENTS_REQUEST: 'DELETE_REQUIRED_DOCUMENTS_REQUEST',
    DELETE_REQUIRED_DOCUMENTS_SUCCESS: "DELETE_REQUIRED_DOCUMENTS_SUCCESS",
    DELETE_REQUIRED_DOCUMENTS_FAILURE: "DELETE_REQUIRED_DOCUMENTS_FAILURE",
    DELETE_REQUIRED_DOCUMENTS_RESET: "DELETE_REQUIRED_DOCUMENTS_RESET",
}

// =========================================
// Send Document Request
// =========================================
export const GetSentDocumentRequest: any = {
    GET_SENT_DOCUMENT_REQUEST_REQUEST: 'GET_SENT_DOCUMENT_REQUEST_REQUEST',
    GET_SENT_DOCUMENT_REQUEST_SUCCESS: "GET_SENT_DOCUMENT_REQUEST_SUCCESS",
    GET_SENT_DOCUMENT_REQUEST_FAILURE: "GET_SENT_DOCUMENT_REQUEST_FAILURE",
    GET_SENT_DOCUMENT_REQUEST_RESET: "GET_SENT_DOCUMENT_REQUEST_RESET"
}

export const SentDocumentRequest: any = {
    SENT_DOCUMENT_REQUEST_REQUEST: 'SENT_DOCUMENT_REQUEST_REQUEST',
    SENT_DOCUMENT_REQUEST_SUCCESS: "SENT_DOCUMENT_REQUEST_SUCCESS",
    SENT_DOCUMENT_REQUEST_FAILURE: "SENT_DOCUMENT_REQUEST_FAILURE",
    SENT_DOCUMENT_REQUEST_RESET: "SENT_DOCUMENT_REQUEST_RESET"
}

export const DeleteDocumentRequest: any = {
    DELETE_DOCUMENT_REQUEST_REQUEST: 'DELETE_DOCUMENT_REQUEST_REQUEST',
    DELETE_DOCUMENT_REQUEST_SUCCESS: "DELETE_DOCUMENT_REQUEST_SUCCESS",
    DELETE_DOCUMENT_REQUEST_FAILURE: "DELETE_DOCUMENT_REQUEST_FAILURE",
    DELETE_DOCUMENT_REQUEST_RESET: "DELETE_DOCUMENT_REQUEST_RESET"
}

// =========================================
// Receive Document Request
// =========================================
export const GetReceiveDocumentRequest: any = {
    GET_RECEIVE_DOCUMENT_REQUEST_REQUEST: 'GET_RECEIVE_DOCUMENT_REQUEST_REQUEST',
    GET_RECEIVE_DOCUMENT_REQUEST_SUCCESS: "GET_RECEIVE_DOCUMENT_REQUEST_SUCCESS",
    GET_RECEIVE_DOCUMENT_REQUEST_FAILURE: "GET_RECEIVE_DOCUMENT_REQUEST_FAILURE",
    GET_RECEIVE_DOCUMENT_REQUEST_RESET: "GET_RECEIVE_DOCUMENT_REQUEST_RESET"
}

export const DownloadDocumentRequest: any = {
    DOWNLOAD_DOCUMENT_REQUEST_REQUEST: 'DOWNLOAD_DOCUMENT_REQUEST_REQUEST',
    DOWNLOAD_DOCUMENT_REQUEST_SUCCESS: "DOWNLOAD_DOCUMENT_REQUEST_SUCCESS",
    DOWNLOAD_DOCUMENT_REQUEST_FAILURE: "DOWNLOAD_DOCUMENT_REQUEST_FAILURE",
    DOWNLOAD_DOCUMENT_REQUEST_RESET: "DOWNLOAD_DOCUMENT_REQUEST_RESET"
}

export const DeleteReceiveDocumentRequest: any = {
    DELETE_RECEIVE_DOCUMENT_REQUEST_REQUEST: 'DELETE_RECEIVE_DOCUMENT_REQUEST_REQUEST',
    DELETE_RECEIVE_DOCUMENT_REQUEST_SUCCESS: "DELETE_RECEIVE_DOCUMENT_REQUEST_SUCCESS",
    DELETE_RECEIVE_DOCUMENT_REQUEST_FAILURE: "DELETE_RECEIVE_DOCUMENT_REQUEST_FAILURE",
    DELETE_RECEIVE_DOCUMENT_REQUEST_RESET: "DELETE_RECEIVE_DOCUMENT_REQUEST_RESET"
}

// =========================================
// Download History
// =========================================
export const GetDownloadHistory: any = {
    GET_DOWNLOAD_HISTORY_REQUEST: 'GET_DOWNLOAD_HISTORY_REQUEST',
    GET_DOWNLOAD_HISTORY_SUCCESS: "GET_DOWNLOAD_HISTORY_SUCCESS",
    GET_DOWNLOAD_HISTORY_FAILURE: "GET_DOWNLOAD_HISTORY_FAILURE",
    GET_DOWNLOAD_HISTORY_RESET: "GET_DOWNLOAD_HISTORY_RESET"
}

export const SaveDownloadHistory: any = {
    SAVE_DOWNLOAD_HISTORY_REQUEST: 'SAVE_DOWNLOAD_HISTORY_REQUEST',
    SAVE_DOWNLOAD_HISTORY_SUCCESS: "SAVE_DOWNLOAD_HISTORY_SUCCESS",
    SAVE_DOWNLOAD_HISTORY_FAILURE: "SAVE_DOWNLOAD_HISTORY_FAILURE",
    SAVE_DOWNLOAD_HISTORY_RESET: "SAVE_DOWNLOAD_HISTORY_RESET"
}

export const DeleteDownloadHistory: any = {
    DELETE_DOWNLOAD_HISTORY_REQUEST: 'DELETE_DOWNLOAD_HISTORY_REQUEST',
    DELETE_DOWNLOAD_HISTORY_SUCCESS: "DELETE_DOWNLOAD_HISTORY_SUCCESS",
    DELETE_DOWNLOAD_HISTORY_FAILURE: "DELETE_DOWNLOAD_HISTORY_FAILURE",
    DELETE_DOWNLOAD_HISTORY_RESET: "DELETE_DOWNLOAD_HISTORY_RESET"
}

// =========================================
// Summary
// =========================================

export const RequestedDocumentSummary: any = {
    REQUESTED_DOCUMENT_SUMMARY_REQUEST: 'REQUESTED_DOCUMENT_SUMMARY_REQUEST',
    REQUESTED_DOCUMENT_SUMMARY_SUCCESS: "REQUESTED_DOCUMENT_SUMMARY_SUCCESS",
    REQUESTED_DOCUMENT_SUMMARY_FAILURE: "REQUESTED_DOCUMENT_SUMMARY_FAILURE",
    REQUESTED_DOCUMENT_SUMMARY_RESET: "REQUESTED_DOCUMENT_SUMMARY_RESET"
}

export const SentDocumentSummary: any = {
    SENT_DOCUMENT_SUMMARY_REQUEST: 'SENT_DOCUMENT_SUMMARY_REQUEST',
    SENT_DOCUMENT_SUMMARY_SUCCESS: "SENT_DOCUMENT_SUMMARY_SUCCESS",
    SENT_DOCUMENT_SUMMARY_FAILURE: "SENT_DOCUMENT_SUMMARY_FAILURE",
    SENT_DOCUMENT_SUMMARY_RESET: "SENT_DOCUMENT_SUMMARY_RESET"
}

export const ReRender: any = {
    RE_RENDER_REQUEST: "RE_RENDER_REQUEST",
    RE_RENDER_RESET: "RE_RENDER_RESET"
}

//=========================================
// Column Save
//=========================================
export const SaveColumn: any = {
    SAVE_COLUMN_REQUEST: 'SAVE_COLUMN_REQUEST',
    SAVE_COLUMN_SUCCESS: "SAVE_COLUMN_SUCCESS",
    SAVE_COLUMN_FAILURE: "SAVE_COLUMN_FAILURE",
    SAVE_COLUMN_RESET: "SAVE_COLUMN_RESET"
}

export const AllTableColumns: any = {
    ALL_TABLE_COLUMN_REQUEST: 'ALL_TABLE_COLUMN_REQUEST',
    ALL_TABLE_COLUMN_SUCCESS: "ALL_TABLE_COLUMN_SUCCESS",
    ALL_TABLE_COLUMN_FAILURE: "ALL_TABLE_COLUMN_FAILURE",
    ALL_TABLE_COLUMN_RESET: "ALL_TABLE_COLUMN_RESET"
}