export const complianceMap = {
    "complianceId": "Compliance ID",
    "complianceCategoryName": "Compliance Category",
    "clientName": "Client",
    "partnerName": "Partner",
    "clientConsumerNumber": "Client Consumer Number",
    "clientAccountNumber": "Client Account Number",
    "contactId": "Contact ID",
    "client": "Client",
    "complianceTypeName": "Compliance Type",
    "dtReport": "Report Date",
    "descriptionReported": "Description",
    "complianceChannelName": "Compliance Channel",
    "reportedBy": "Reported by",
    "accountId": "Account ID",
    "complianceStatusName": "Compliance Status ",
    "bankruptcyType": "Bankruptcy Type",
    "complianceModeName": "Compliance Mode",
    "complianceReasonName": "Compliance Reason",
    "isValidationRequired": "Validation Required",
    "createdBy": "Created By",
    "createdOn": "Created On",
    "details": "Details",
    "dtResolution": "Resolution Date",
    "dtFiling": "Filing Date",
    "complianceChannel": "Channel Code",
    "complianceStatus": "Status Code",
    "complianceReason": " Reason Code",
    "isRegulatory": "Is Regulatory",
    "dtFirstSla": "First SLA Date",
    "dtLastSla": "Last SLA Date",
    "remarkComment": "Comment",
    "regulatorybodyName": "Regulatory Body",
    "caseFileNumber": 'Case File Number',
    "principleAmt": 'Principle Amount',
    "interestAmt": 'Interest Amount',
    "feeAmt": 'Fee Amount',
    "totalAmt": 'Total Amount',
    "courtCity": 'Jurisdiction',
    "originalAccountNumber": 'Original Account Number',
    "complianceSubType": "Compliance Sub Type Code",
    "complianceSubTypeName": "Compliance Sub Type",
    "dtFirstSlaDiff": "Days Until First SLA",
    "dtLastSlaDiff": "Days Until Last SLA",
    "isAdditionalTimeRequired": "Additional Time Required"
}

export const accountMap = {
    "clientConsumerNumber": "Client Consumer Number",
    "clientName": "Client Name",
    "consumerName": "Consumer Name",
    "consumerSSN": "Consumer SSN",
    "equabliAccountNumber": "Equabli Account Number",
    "originalAccountNumber": "Original Account Number",
    "clientAccountNumber": "Client Account Number",
    "queue": "Queue",
    "accountStatus": "Status",
    "productType": "Type Of Asset",
    "chargeOffDate": "Charge-Off Date",
    "assignedPartner": "Partner",
    "accountQueue": "Account Queue",
    "eqvscore": "EQV",
    "SOLDate": "SOL Date",
    "chargeOffBalance": "Charge-off Balance",
    "currentBalance": "Current Balance",
    "consumerAddressState": "State",
    "accountReason": "Account Reason",
    "queueStatusId": "Queue Status ID",
    "consumerId": "Consumer ID",
    "complianceIds": 'Compliances'
}

export const consumerMap = {
    "assignedPartner": "Partner",
    "clientConsumerNumber": "Client Consumer Number",
    "clientId": "Client ID",
    "clientName": "Client Name",
    "consumerAddressAndState": "State",
    "consumerName": "Consumer Name",
    "consumerSSN": "Consumer SSN",
    "equabliConsumerNumber": "Equabli Consumer Number",
    "exclusionReason": "Exclusion Reason",
    "isExcluded": "Excluded",
    "accountStatus": "Account Status",
    "originalAccountNumber": "Original Account Number",
    "partnerId": "Partner ID",
    "clientAccountNumber": " Client Account Number",
    "recordNumber": "Record Number",
}

export const inventoryMap = {
    "clientConsumerNumber": "Client Consumer Number",
    "accountQueueStatus": "Account Queue Status",
    "accountReason": "Current Queue Reason",
    "assignedPartner": "Assigned Partner",
    "clientId": "Client ID",
    "consumerId": "Equabli Consumer Number",
    "consumerName": "Consumer Name",
    "openAccountCount": "Open Account Count",
    "partnerId": "Partner ID",
    "clientPortfolioId": "Client Portfolio Number",
    "portfolioId": "Equabli Portfolio Number",
    "queue": "Current Queue",
    "placementId": "Placement ID",
    "accountStatus": "Current Queue Status",
    "queueId": "Queue ID",
    "queueReasonId": "Queue Reason ID",
    "queueStatusId": "Queue Status ID",
    "recordNumber": "Record Number",
    "requestedAccountCount": "Requested Account Count",
    "clientName": "Client Name",
    "originalAccountNumber": "Original Account Number",
    "equabliAccountNumber": "Equabli Account Number",
    "clientAccountNumber": "Client Account Number",
    "complianceIds": "Compliances"
}


export const myRequestMap = {
    "servicingRequestId": "Request ID",
    "request": "Request",
    "fromQueue": "From Queue",
    "requestStatus": "Request Status",
    "category": "Category",
    "toQueue": "To Queue",
    "noOfAccount": "No Of Account",
    "requester": "Requester",
    "priority": "Priority",
    "dueDate": "Due Date",
    "requestDate": "Request Date",
    "workflowStatus": "WorkFlow Status",
    "batchDescription": "Batch Description",
    "modifiedBy": "Modified By",
    "approved": "Approved",
    "approvedRejectedBy": "Approved Rejected By",
    "modifiedDate": "Modified Date",
    "rag": "RAG",
    "countRecord": "Count Record",
    "createdBy": "Created By",
    "priorityExecution": "Priority Execution",
    "dtmDueExecution": "Due Date",
    "dtmUtcCreate": "Create Date",
    "selectionCriteria": "Selection Criteria",
    "updatedBy": "Updated By",
    "actionBy": "Action By",
    "dtmUtcUpdate": "Update Date",
    "actionRemarks": "Action Remark",
    "toAccountReason": 'To Account Reason'
}

export const actionQueueMap = {
    "clientName": "Client Name",
    "consumerName": "Consumer Name",
    "originalAccountNumber": "Original Account Number",
    "equabliAccountNumber": "Equabli Account Number",
    "portfolioId": "Portfolio ID",
    "fromQueue": "From Queue",
    "fromAccountStatus": "From Account Status",
    "fromAccountReason": "From Account Reason",
    "toQueue": "To Queue",
    "toAccountReason": 'To Account Reason',
    "toAccountStatus": "To Account Status",
    "placementBalance": "Placement Balance",
    "currentBalance": "Current Balance",
    "attributeChangeSoFar": "Attribute Change so Far"
}

export const alertMap = {
    "alertDefinitionId": "Alert definition ID",
    "alertTypeId": "Alert type ID",
    "alertGroupId": "Alert group ID",
    "alertTypeVal": "Alert type",
    "alertGroupVal": "Alert Group",
    "shortName": "Short Name",
    "description": "Description",
    "priority": "Priority",
    "emailSubject": "Email Subject",
    "emailBody": "Email Body",
    "emailId": "Email IDs",
    "sqlStatement1": "SQL statement 1",
    "sqlStatement2": "SQL statement 2",
    "comparisonOperator": "Comparison Operator",
    "thresholdDataType": "Threshold Type",
    "thresholdValue": "Threshold Value",
    "recordStatusVal": "Status"
}

export const schedulerMap = {
    "batchSchedulerId": "Batch Scheduler ID",
    "shortName": "Short Name",
    "description": "Description",
    "batchSchedulerGroupVal": "Group Value",
    "url": "URL",
    "urlMethod": "URL method",
    "urlParameter": "URL parameter",
    "expression": "Expression",
    "recordStatusVal": "Record Status",
    "dtmUtcSchedule": "Schedule Last Triggered",
    // "dtmUtcLastTrigger": "Schedule Last Triggered",
    "dtmUtcNextTrigger": "Schedule Next Triggered"
}

export const processDashboardMap = {
    "alertLogId": 'Alert Log ID',
    "dtmUtcStartTime": "Start Time",
    "dtmUtcEndTime": "End Time",
    "executionStatusVal": "Status",
    "logDescription": "Log Description",
    "id": 'ID',
    "direction": 'Direction',
    "filePath": 'File Path',
    "dateTimeStarted": 'Date Time Start',
    "dateTimeEnded": "Date Time Ended",
    "batchStatus": 'Batch Status',
    "recordInitiated": 'Record Initiated',
    "recordSuccessful": "Record Successful",
    "recordErrored": "Record Error",
    "batchSchedulerLogId": "Log ID",
    "batchSchedulerId": "Batch Scheduler ID",
    "shortName": "Short Name",
    "description": "Description",
    "batchSchedulerGroupVal": "Group",
    "url": "Url",
    "urlMethod": "Url Method",
    "urlParameter": "Url Parameter",
    "expression": "Expression",
    "StartTime": "Start Time",
    "EndTime": "End Time",
    "Status": "Status",
    "LogDescription": "Log Description",
    "dtmUtcSchedule": "Schedule Time",
    "dtmUtcLastTrigger": "Last Triggered At",
    "dtmUtcNextTrigger": "Next Triggered At",
    "emailStatusVal": 'Email Status'
}

export const solMap = {
    "accountId": "Account ID",
    "clientName": "Client Name",
    "dtClientStatute": "Client SOL date",
    "dtEquabliStatute": "Equabli SOL date",
    "equabliPortfolioId": "Portfolio ID"
}

export const placementMap = {
    "clientAccountNumber": 'Client Account Number',
    "clientName": 'Client Name',
    "partnerName": 'Partner Name',
    "jobScheduleId": 'Job Schedule ID',
    "reconciliationStatus": "Reconciliation Status"
}

export const eligiblePartnerMap = {
    "keyContacts": "Key Contacts",
    "companyInformation": "Company Information",
    "accountTypeServiced": "Account Type Serviced",
    "companyLicenses": "Company Licenses",
    "servicesOffered": "Product Type Serviced",
    "agents": "Agents",
    "capacity": "Capacity",
    "commissionRate": "Commission Rate",
    "partnerStatus": "Status",
    "compliance": "Compliance",
    "collections": "Collections"
}