# This is a workflow for execute EQ-Docs UI QA Deployment

name: EQ-SSO UI QA Deployment
on:
  push:
    branches: qa
  workflow_dispatch:
jobs:
   # This workflow contains a single job called "build"
 call-eks-deployment-ui-lib-with-cd:
  uses: Equabli/eq-devops-iaac/.github/workflows/eks-ui-deployment-with-cd.yml@main
  with:
   ecr-repository-path: eks-eq-sso-ui-qa
   check-out-branch: qa
   enviornment: qa
   service-name: single-sign-on
   major-version: 1
   deployment-file-name: sso-ui-deployment.yaml
   yaml-update-branch: deployment
  secrets:
    env-config-file: ${{ secrets.QA_ENV }}
