# This is a workflow for execute EQ-Docs UI Stage Deployment

name: EQ-SSO UI Stage Deployment
on:
  push:
    branches: stage
  workflow_dispatch:
jobs:
   # This workflow contains a single job called "build"
 call-eks-deployment-ui-lib-with-cd:
  uses: Equabli/eq-devops-iaac/.github/workflows/eks-ui-deployment-with-cd.yml@main
  with:
   ecr-repository-path: eks-eq-sso-ui-stage
   check-out-branch: stage
   enviornment: stage
   service-name: single-sign-on
   major-version: 1
   deployment-file-name: sso-ui-deployment.yaml
   yaml-update-branch: deployment
  secrets:
    env-config-file: ${{ secrets.STAGE_ENV }}
